version: '3.8'

services:

  rust_api:

    build:
      context: .
      dockerfile: Dockerfile

    expose:
      - "8080"

    deploy:
      replicas: 4

    restart: always

    networks:
      - front-network

  proxy:

    image: nginx:latest


    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    
    ports:
      - "8080:8080"

    depends_on: 
      - rust_api

    networks:
      - front-network

networks:
  front-network:
    driver: bridge